### ISSUE TITLE
Twitter status (tweet) as article?

### ISSUE THREAD

**Issue by mattpal** [ageitgey/node-unfluff#29]
In my project I found a need to mine images from tweets as "articles".  People sometimes tweet links to articles, sometimes they tweet pictures from an event.

I added a little hack to do this that looks at the url to see if it's a tweet, then looks for a image reference:

```
    var rgxTwitterStatus = /https:\/\/twitter.com\/[^\/]+\/status/,
          rgxTwitterImage = /<img src="(https:\/\/pbs.twimg.com\/media\/[^"]+)/;

    if (url && rgxTwitterStatus.test(url)) {
        if (m = html.match(rgxTwitterImage)) {
            article.image = m[1];
        }
    }
```

I'm just posting it since it I thought it might be generally useful, and since I don't know coffee script or the unfluff codebase well enough to try and submit a pull req.

**Comment by ageitgey** [comment]
In the latest version, the "image" data returned by unfluff for a tweet url should be the image the user uploaded. So you shouldn't have to do anything extra to get this anymore.

Example:
```
$ curl -s https://twitter.com/BuckyIsotope/status/605093290220781568 | unfluff | jq .image

"https://pbs.twimg.com/media/CGW5JDXUIAAxLVQ.jpg:large"
```
