### ISSUE TITLE
Typo in extractor#isHighlinkDensity ?

### ISSUE THREAD

**Issue by dminkovsky** [ageitgey/node-unfluff#32]
[Line 378 of extractor.coffee](https://github.com/ageitgey/node-unfluff/blob/01ca44cea69b9d6cdfbd3d9e83586037851be4b0/src/extractor.coffee#L378) is currently:

```
linkText = sb.join('')
``` 

which doesn't really make sense... shouldn't it be this?:

```
linkText = sb.join(' ')
```

Changing it to this, however, causes the `polygon_video` test to break. Not sure how to address this, or, really, how to make complete sense of the `isHighlinkDensity` function. The idea behind the function is perfectly clear, but how the function is "tuned" doesn't really make sense:

```
linkDivisor = numberOfLinkWords / wordsNumber
score = linkDivisor * numberOfLinks

score >= 1.0
```

Maybe a bad question to ask about a heuristic, but why is this the heuristic?

**Comment by ageitgey** [comment]
Yes, nice find! Thanks for pointing out that typo. I'm pushing a fix. 

As far as the heuristic, that section based on the original [Goose code](https://github.com/GravityLabs/goose/wiki). I cleaned up the naming to make the flow a little easier to follow, but I didn't come up with that heuristic originally.
