### ISSUE TITLE
Description should try to get meta[property="og:description"]

### ISSUE THREAD

**Issue by joanamelo** [ageitgey/node-unfluff#40]
This issue is similar to the og:title field Issue that was solved some months ago.

An example of poor processing is the result of a twitter status url.

***Example URL:*** https://twitter.com/github/status/609116267891580928

***Result:***

{ 
  title: 'GitHub on Twitter',
  favicon: '//abs.twimg.com/favicons/favicon.ico',
  description: undefined,
  keywords: undefined,
  lang: 'en',
  canonicalLink: 'https://twitter.com/github/status/609116267891580928',
  tags: [],
  image: 'https://pbs.twimg.com/profile_images/426158315781881856/sBsvBbjY_400x400.png',
  videos: [],
  text: 'Log in\n\nTo bring you Twitter, we, and our partners, use cookies on our and other websites. Cookies help personalise Twitter content, tailor Twitter Ads (.......)'
}

***og:description of that page:*** “Check out the full list of @codeconf sessions and grab your ticket now! See you in Nashville in 2 weeks: http://t.co/9mynYt0VPc”

**Comment by ageitgey** [comment]
Thanks! Submitting a fix for this.

**Comment by joanamelo** [comment]
Awesome! Thank you :)
