### ISSUE TITLE
Extract author

### ISSUE THREAD

**Issue by PetrKaleta** [ageitgey/node-unfluff#48]
Find first valid value (trimmed length in interval `0..100`) of:

1. `meta[name="author"]`
2. `[rel="author"]`
3. `[class="author"], [class="writer"], [class="writtenby"]`
4. `[id="author"], [id="writer"], [id="writtenby"]`

**Comment by snellingio** [comment]
Looks like we're getting support in #49

**Comment by ageitgey** [comment]
Check out v1.0.0 and see if it meets your needs! :)
