### ISSUE TITLE
do you support open graph

### ISSUE THREAD

**Issue by yawhide** [ageitgey/node-unfluff#52]
Hello,

Do you support open graph? If not, do you have any plans to support open graph?

thanks

**Comment by ageitgey** [comment]
Can you be more specific? Support in what way?

In general, unfluff will pull data from `og:*` tags when it makes sense for things like photos or authors. But unfluff is not designed primarily to be a client library for pulling open graph data from webpages.

**Comment by yawhide** [comment]
so your library supports getting the description from the `<meta name='description'` tag. Would it be able to get the description from the `<meta name='og:description'` tag.

**Comment by ageitgey** [comment]
Yes, it tries both:

https://github.com/ageitgey/node-unfluff/blob/b3d1c6bb106f4bb8106f78bd55851c411333d0eb/src/extractor.coffee#L164

**Comment by yawhide** [comment]
ok thanks
