### ISSUE TITLE
What coffee does unfluff drink?

### ISSUE THREAD

**Issue by bennyk** [ageitgey/node-unfluff#54]
Seeing this error in "make": -

Error: unrecognized option: --js
  at OptionParser.exports.OptionParser.OptionParser.parse (.../node-unfluff/node_modules/coffee-script/lib/coffee-script/optparse.js:51:19)

There are many kinds of coffee out there on internet. Which coffee does unfluff use? Me is http://coffeescript.org/

This patch seem to fix it: -

diff --git a/Makefile b/Makefile
index 557d91d..b63a69e 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ SRC = $(shell find "$(SRCDIR)" -name "_.coffee" -type f | sort)
 LIB = $(SRC:$(SRCDIR)/%.coffee=$(LIBDIR)/%.js)
 TEST = $(shell find "$(TESTDIR)" -name "_.coffee" -type f | sort)

-COFFEE=node_modules/.bin/coffee --js
+COFFEE=node_modules/.bin/coffee -c
 MOCHA=node_modules/.bin/mocha --compilers coffee:coffee-script-redux/register -r test-setup.coffee -u tdd -R dot
 CJSIFY=node_modules/.bin/cjsify --minify
 SEMVER=node_modules/.bin/semver

Finally there isn't any Make instruction. I thought it will be nice to have one. Thanks for the awesome coffee!

**Comment by sahasd** [comment]
Getting error

possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit. Trace

What should I do?

**Comment by ageitgey** [comment]
The current version it uses is specified in `package.json`:

`   "coffee-script-redux": "2.0.0-beta7",`

Just doing `npm install` and 'make all' should be all that is needed.

`coffee-script-redux` was a fork of `coffeescript` aimed at becoming coffeescript 2.0. It's pretty much abandoned now though, so I'll switch this back to normal `coffeescript` when I have a free moment and I'll also add better build instructions. Thanks!
