### ISSUE TITLE
Deprecated modules

### ISSUE THREAD

**Issue by riyaznet** [ageitgey/node-unfluff#58]
Seeing following warnings when installing unfluff -
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

Pls update

**Comment by alihesari** [comment]
I have this problem. What is the solution?!

**Comment by ageitgey** [comment]
I just published a new version (3.0.0) that hopefully fixes this. Sorry about that.
