### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by AndrejGajdos** [ageitgey/node-unfluff#79]
For some url's I get **400 Bad Request** results:

[podsavethepeople.com](https://www.podsavethepeople.com/), [www.trumptaxscam.org](https://www.trumptaxscam.org/impact-of-the-trump-tax-scam-by-state#Nebraska)

**Comment by ageitgey** [comment]
This library doesn't make any http requests, so I'm guessing this problem must be related to how you are querying those sites (separate from this library). Wish I had a better answer for you.

**Comment by AndrejGajdos** [comment]
Thanks for response, I will check it out.
