### ISSUE TITLE
loadash needs update

### ISSUE THREAD

**Issue by cekvenich** [ageitgey/node-unfluff#91]
Npm audit is reporting unfluf as not secure due to it using old version of lodash.
unfluf needs version 4.17.15 or later of loadash.

**Comment by ageitgey** [comment]
Thanks for letting me know! I'm on vacation at the moment but hope to update it next week.

**Comment by cekvenich** [comment]
eta?

**Comment by ageitgey** [comment]
There's no v4.17.15, but I bumped lodash to the latest version in #92.

**Comment by ageitgey** [comment]
published as v3.2.0

**Comment by cekvenich** [comment]
Thank you, I tested and it seems to work.
